apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
namespace: default
metadata:
  name: traditional-error-rate-check
spec:
  args:
    - name: canary-service
  metrics:
    - name: error-rate
      interval: 30s # Cùng chu kỳ với AI
      count: 5      # Cùng số lần đếm với AI
      successCondition: result[0] < 0.05
      # failureLimit: Nếu quá 5% ngay lần đầu thì fail luôn, hoặc bạn có thể để mặc định
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{service="{{args.canary-service}}", status=~"5.."}[1m])) 
            / 
            clamp_min(sum(rate(http_requests_total{service="{{args.canary-service}}"}[1m])), 0.001)