apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd # Nơi Argo CD đang chạy
spec:
  project: default
  source:
    # Tương ứng với --repo https://kubernetes.github.io/ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.3 # Bạn nên chốt một phiên bản cụ thể để ổn định
    helm:
      values: |
        controller:
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    # Tương ứng với --namespace ingress-nginx
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Tương ứng với --create-namespace
      - CreateNamespace=true
