apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rl-canary-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/thuanthentran/dqn-lstm-agent-driven-canary-release.git
    targetRevision: main
    path: gitops/app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
  - group: ""
    kind: Service
    name: my-app-stable
    namespace: default
    jsonPointers:
    - /spec/selector
  - group: ""
    kind: Service
    name: my-app-canary
    namespace: default
    jsonPointers:
    - /spec/selector
  - group: networking.k8s.io
    kind: Ingress
    name: my-app-ingress
    namespace: default
    jsonPointers:
    - /metadata/annotations/nginx.ingress.kubernetes.io~1canary
    - /metadata/annotations/nginx.ingress.kubernetes.io~1canary-weight
    - /metadata/annotations/nginx.ingress.kubernetes.io~1canary-by-header
    - /metadata/annotations/nginx.ingress.kubernetes.io~1canary-by-header-value
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    # Retry policy cho hết hạn image cleanup
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
